name: "Podcast Generator"
author: "RDS"
description: "Generate a feed for a podcast from a YAML file"
runs:
  using: "docker"
  main: "Dockerfile"
branding:
  color: "red"
  icon: "git-branch"
inputs:
  email:
    description: "The committer's Email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The committer's name"
    required: true
    default: ${{ github.actor }}